# Generated by Django 5.0.6 on 2024-05-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_rename_email_tarea_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='correo_electronico',
            new_name='email',
        ),
    ]
